### ISSUE TITLE
邮箱登录不了

### ISSUE THREAD

**Issue by ghost** [SunRelease/BaiduSVIP#3]
要求我用手机验证

**Comment by 23Xor-7D** [comment]
第一个账号邮箱登录不了，第四个能登邮箱但提示账号不存在

**Comment by 23Xor-7D** [comment]
加一下，第三个也是

**Comment by ghost** [comment]
四个都用不了，第一个邮箱需要手机验证，后三个账号不存在，是有什么神必操作🐴？

**Comment by YanDididi** [comment]
> 第一个账号邮箱登录不了，第四个能登邮箱但提示账号不存在

总结一下就是都不能用

**Comment by ghost** [comment]
我又回去看了一下，确实是直接账密登录
不存在具体是输入账密→密码错误→找回密码→账号不存在
所以一定是有孤儿把密保邮箱换了，从此自用
建议搞个邮箱自动转发，转发到别的一个邮箱，以免有人换绑

**Comment by ghost** [comment]
这些孤儿们还挺能整的，4个都改了，强烈建议今天就开自动转发，邮箱别给密码，直接给转发邮箱的账密就行了
